version: '2.1'

services:
  rpa-dg-docassembly-api:
    build:
      context: .
    image: hmctspublic.azurecr.io/dg/docassembly:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_API_BASE_URI=http://idam-api:8080
      - S2S_BASE_URI=http://service-auth-provider-app:8489
      - DM_STORE_APP_URL=http://dm-store:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
      # these environment variables are used by java-logging library
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=rpa-dg-docassembly
      - REFORM_TEAM=dg-docassembly
      - REFORM_ENVIRONMENT=docker
      - DOCMOSIS_ACCESS_KEY=
      - DOCMOSIS_TEMPLATES_ENDPOINT_AUTH=
      #      endpoint toggles
      - ENABLE_FORM_DEFINITION_ENDPOINT=true
      - ENABLE_TEMPLATE_RENDITION_ENDPOINT=true
    ports:
      - 4631:$SERVER_PORT
