---
version: '2.1'

services:
  rpa-dg-docassembly-api:
    build:
      context: .
    image: hmctspublic.azurecr.io/dg/docassembly:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_API_BASE_URI=http://idam-api:8080
      - S2S_BASE_URI=http://service-auth-provider-api:8489
      - DM_STORE_APP_URL=http://dm-store:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
      # these environment variables are used by java-logging library
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=rpa-dg-docassembly
      - REFORM_TEAM=dg-docassembly
      - REFORM_ENVIRONMENT=docker
      - DOCMOSIS_ACCESS_KEY=
      - DOCMOSIS_TEMPLATES_ENDPOINT_AUTH=
      #      endpoint toggles
      - ENABLE_FORM_DEFINITION_ENDPOINT=true
      - ENABLE_TEMPLATE_RENDITION_ENDPOINT=true
    ports:
      - 8080:8080

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
    environment:
      - jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
#      - Add key for any microservice that will be used
      - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
      - microserviceKeys_dg_docassembly_api=AAAAAAAAAAAAAAAA
      #      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-app
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-app
      - PACKAGES_VERSION=unkown
      - TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8489

  idam-api:
    image: hmcts.azurecr.io/hmcts/tidam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_DATASOURCE_USERNAME=idam-username
      - SPRING_DATASOURCE_PASSWORD=idam-password
      - SPRING_MAIL_HOST=smtp-server
      - IDAM_TESTING_SUPPORT_ENABLED="true"
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_WEBSHOW=AAAAAAAAAAAAAAAA
      - IDAM_WEBSHOW_WHITELIST=http://localhost:8080/oauth2redirect
      - REFORM_SERVICE_NAME=idam-api
      - REFORM_TEAM=idam
      - REFORM_ENVIRONMENT=local
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
      - 4501:8080
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  idam-database:
    image: postgres
    environment:
      - POSTGRES_USER=idam-username
      - POSTGRES_PASSWORD=idam-password
      - POSTGRES_DB=idam
    ports:
      - 5434:5432

  dm-store:
    image: hmctspublic.azurecr.io/dm/store:latest
    command: --wait-for-database 30
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
      - GOV_NOTIFY_API_KEY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dm-store-db:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8489
      - S2S_NAMES_WHITELIST=em_npa_app,sscs,divorce,ccd,em_gw,ccd_gw,em_stitching_api,em_ccd_orchestrator,dg_docassembly_api
      - http_proxy=
      - https_proxy=
      - no_proxy=
      #      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
      #      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=dm-store
      - PACKAGES_VERSION=unkown
    links:
      - dm-store-db
      - service-auth-provider-api
    depends_on:
      - dm-store-db
      - service-auth-provider-api
    ports:
      - 4603:8080

  dm-store-db:
    image: postgres
    environment:
      - POSTGRES_USER=evidence
      - POSTGRES_PASSWORD=evidence
      - POSTGRES_DB=evidence

