spring:
  application:
    name: Document Assembly API
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5000/o}
        registration:
          oidc:
            client-id: microservicekey-dg-docassembly-api
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: '/'
      exposure:
        include:
         - health
         - info
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
  info:
     build:
       enabled: true # Whether to enable build info.
     defaults:
       enabled: true # Whether to enable default info contributors.
     env:
       enabled: true # Whether to enable environment info.
     git:
       enabled: true # Whether to enable git info.
       mode: simple # Mode to use to expose git information.

info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:dg-docassembly}
    name: ${PACKAGES_NAME:cor}
#    version: ${PACKAGES_VERSION:unknown}

auth:
  idam:
    client:
      baseUrl: ${IDAM_API_BASE_URI:http://localhost:5000}
  provider:
    service:
      client:
        baseUrl: ${S2S_BASE_URI:http://localhost:4502}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d30268e8-8979-4579-8d58-010dbe03a1e6}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on


idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
    microservice: dg_docassembly_api
  s2s-authorised:
    services: ${S2S_NAMES_WHITELIST:sscs,divorce,ccd,em_gw,jui_webapp,pui_webapp}

template-management-api:
  base-url: ${DOCMOSIS_TEMPLATES_ENDPOINT:https://docmosis-development.platform.hmcts.net}
  auth: ${DOCMOSIS_TEMPLATES_ENDPOINT_AUTH:SOMETHING}
  resource: '/templates/'

docmosis:
  accessKey: ${DOCMOSIS_ACCESS_KEY:SOMETHING}
  convert.endpoint: ${DOCMOSIS_ENDPOINT:https://docmosis-development.platform.hmcts.net/rs/render}

dm-store-app:
  base-url: ${DM_STORE_APP_URL:http://localhost:4603}

endpoint-toggles:
  form-definitions: ${ENABLE_FORM_DEFINITION_ENDPOINT:true}
  template-renditions: ${ENABLE_TEMPLATE_RENDITION_ENDPOINT:true}

# Delete when issueOverride variable is no longer used in SecurityConfiguration.class
oidc:
  issuer: ${OIDC_ISSUER_BASE_URI:http://localhost:8080/openam/oauth2/hmcts}