java:
  applicationPort: 8080
  image: hmctspublic.azurecr.io/dg/docassembly:latest
  readinessDelay: 30
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 30
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  aadIdentityName: dg
  keyVaults:
    dg-docassembly:
      resourceGroup: dg-docassembly
      secrets:
        - microservicekey-dg-docassembly-api
        - AppInsightsInstrumentationKey
        - docmosis-templates-auth
        - docmosis-access-key
  environment:
    IDAM_API_BASE_URI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_WEBSHOW_WHITELIST: https://em-show-aat.service.core-compute-aat.internal/oauth2/callback
    DM_STORE_APP_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCMOSIS_TEMPLATES_ENDPOINT: https://docmosis-development.platform.hmcts.net
    DOCMOSIS_ENDPOINT: https://docmosis-development.platform.hmcts.net/rs/render

    REFORM_SERVICE_NAME: dg-docassembly
    REFORM_TEAM: evidence
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: dg-docassembly
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    S2S_NAMES_WHITELIST: em_api,em_gw,ccd_gw,ccd_data,sscs,divorce_document_upload,divorce_document_generator,probate_backend,jui_webapp,pui_webapp,cmc_claim_store
    CASE_WORKER_ROLES: caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    ENABLE_FORM_DEFINITION_ENDPOINT: false
    ENABLE_TEMPLATE_RENDITION_ENDPOINT: true
    SERVER_PORT: 8080
