idam_api_base_uri = "https://idam-api.demo.platform.hmcts.net"
open_id_api_base_uri = "https://idam-api.demo.platform.hmcts.net/o"
oidc_issuer_base_uri = "https://forgerock-am.service.core-compute-idam-demo.internal:8443/openam/oauth2/hmcts"
dns_server="10.96.203.254"
managed_identity_object_id="3c688173-23b0-43aa-a6e5-bb5e982cbd68"
enable_form_definition_endpoint="false"
enable_template_rendition_endpoint="true"