idam_api_base_uri = "https://idam-api.platform.hmcts.net"
docmosis_uri = "https://docmosis.platform.hmcts.net/rs/render"
dns_server="10.96.75.254"
enable_form_definition_endpoint="false"
enable_template_rendition_endpoint="true"
capacity = "2"
